################ English language ##################
[en]
languageName = "En"
languageCode = "en-gb"
contentDir = "content/english"
weight = 1

################ Welsh language ##################
[cy]
languageName = "Cy"
languageCode = "cy-cy"
contentDir = "content/cymraeg"
weight = 2
