############# English navigation ##############

# main menu
[[main]]
name = "Newsletter"
url = "newsletter/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 4

[[main]]
weight = 5
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Projects"
  url = "project/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "About"
  url = "about/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "Team"
  url = "team/"
  weight = 3

# footer menu
[[footer]]
name = "Terms of Service"
url = "terms/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
