############# English navigation ##############

# main menu
[[main]]
weight = 1
url = ""
name = "Home"

[[main]]
weight = 2
url = "about/"
name = "About"

[[main]]
weight = 3
url = "newsletter/"
name = "Newsletter"

[[main]]
weight = 4
url = "plans/"
name = "Plans"

[[main]]
weight = 5
url = "contact/"
name = "Contact"

[[main]]
weight = 6
url = "#"
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  weight = 1
  url = "author/"
  name = "Author"
  
  [[main]]
  parent = "Pages"
  weight = 2
  url = "tags/"
  name = "Tags"
  
  [[main]]
  parent = "Pages"
  weight = 4
  url = "categories/"
  name = "Category"
  

############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "About"

[[footer]]
weight = 2
url = "author/"
name = "Authors"

[[footer]]
weight = 3
url = "conduct/"
name = "Code of Conduct"
