############# English navigation ##############

# main menu
[[main]]
name = "Newsletter"
url = "newsletter/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2


[[main]]
weight = 5
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Toolkit"
  url = "toolkit/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Partners"
  url = "partners/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "About"
  url = "about/"
  weight = 3

  [[main]]
  parent = "Pages"
  name = "Team"
  url = "team/"
  weight = 4

  [[main]]
  parent = "Pages"
  name = "Contact"
  url = "contact/"
  weight = 6

[[main]]
name = "Admin"
hasChildren = true
weight = 5

  [[main]]
  parent = "Admin"
  name = "Events calendar"
  url = "events/"
  weight = 1

  [[main]]
  parent = "Admin"
  name = "Plants spreadsheet"
  url = "plants/"
  weight = 2

  [[main]]
  parent = "Admin"
  name = "Budget spreadsheet"
  url = "budget/"
  weight = 3

  [[main]]
  parent = "Admin"
  name = "Media Pack"
  url = "media/"
  weight = 4

[[main]]
name = "Grant"
hasChildren = true
weight = 6

  [[main]]
  parent = "Grant"
  name = "Grant overview"
  url = "grant/overview/"
  weight = 1

  [[main]]
  parent = "Grant"
  name = "Application"
  url = "grant/application/"
  weight = 2

  [[main]]
  parent = "Grant"
  name = "Purposes"
  url = "grant/purposes/"
  weight = 3

  [[main]]
  parent = "Grant"
  name = "Maintenance"
  url = "grant/maintenance/"
  weight = 4

  [[main]]
  parent = "Grant"
  name = "Performance"
  url = "grant/performance/"
  weight = 5

  [[main]]
  parent = "Grant"
  name = "Project"
  url = "grant/project/"
  weight = 5

# footer menu
[[footer]]
name = "Licensing"
url = "licensing/"
weight = 1
