############# English navigation ##############

# main menu
[[main]]
name = "Newsletter"
url = "newsletter/"
weight = 1

[[main]]
name = "Blog"
url = "blog/"
weight = 2


[[main]]
weight = 5
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Toolkit"
  url = "toolkit/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Partners"
  url = "partners/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "About"
  url = "about/"
  weight = 3

  [[main]]
  parent = "Pages"
  name = "Team"
  url = "team/"
  weight = 4

  [[main]]
  parent = "Pages"
  name = "Events"
  url = "admin/events/"
  weight = 5

  [[main]]
  parent = "Pages"
  name = "Plants"
  url = "admin/plants/"
  weight = 6

  [[main]]
  parent = "Pages"
  name = "Contact"
  url = "contact/"
  weight = 6

# footer menu
[[footer]]
name = "Licensing"
url = "licensing/"
weight = 1
