[build]
publish = "public"
command = "tinacms build && hugo --gc --minify --templateMetrics --templateMetricsHints --buildDrafts --buildExpired --buildFuture --forceSyncStatic"

[build.environment]
HUGO_VERSION = "0.115.1"
GO_VERSION = "1.20.5"
HUGO_BASEURL = "/"
